version: "3.9"
services:
  db:
    image: postgres:15-alpine
    container_name: "Database"
    environment:
      - "POSTGRES_DB=${DB_NAME}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
  server:
    image: python:3.11-alpine
    container_name: "Server"
    env_file:
      - ".env"
    volumes:
      - "./server:/App"
    command: sh -c "cd /App && pip3 install pipenv && pipenv install && pipenv run python main.py"
    ports:
      - "5050:5050"
    depends_on:
      - db
  client:
    image: node:18-alpine
    container_name: "Client"
    volumes:
      - "./client:/home/node/app"
    ports:
      - "3000:3000"
    command: sh -c "cd /home/node/app && npm install && npm start"
  