version: '3.9'
services:
  db:
    image: postgres:15-alpine
    container_name: "Database"
    environment:
      POSTGRES_DB: "izrael"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password123"
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"