version: "3.9"
services:
  db:
    image: postgres:15-alpine
    restart: "always"
    container_name: "Database"
    environment:
      - "POSTGRES_DB=${DB_NAME}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    ports:
      - "${DB_PORT}:5432"
  server:
    image: python:3.11-alpine
    restart: "always"
    container_name: "Server"
    env_file:
      - ".env"
    volumes:
      - "./server:/app"
    command: sh -c "cd /app && pip3 install pipenv && pipenv install && pipenv run python main.py"
    ports:
      - "${SERVER_PORT}:5050"
    depends_on:
      - db
  # client:
  #   build: "./client"
  #   restart: "always"
  #   container_name: "Client"
  #   volumes:
  #     - "./client:/app"
  #     - "/app/node_modules"
  #   ports:
  #     - "${CLIENT_PORT}:3000"
  #   depends_on:
  #     - server
  